### ISSUE TITLE
Implementation Suggestion 

### ISSUE THREAD

**Issue by acalhounRH** [distributed-system-analysis/py-es-bulk#1]
Below is an example of how to use the Elasticsearch parallel_bulk import API, alternatively from stream_bulk, the parallel_ bulk API allows the operator to break up a large request into several threads. additionally added logical to indefinitely re-attempt to index, in conjunction with a truncated backoff based on the write queue (elasticsearch v6.3+ write queue, elasticsearch less than v6.3 use the bulk queue). 

My prototype pbench indexer would create a thread for each host directory found in tools-default, then search for all csv files, parse the content, adding meta to each record then append the record (elasticsearch json document) to the actions list. After parsing the entire csv file and appending all records to the actions list, a bulk_import(a) call would be made.

def bulk_import(a)
 
    actions = copy.deepcopy(a)
    index = True
    #Continue to attempt to index actions indefinitely, until successful.
    #another option would be to set a limit of retries, in order to prevent hanging forever.   
    while index:
        try:
            bulk_status = int((es.cat.thread_pool(thread_pool_patterns='write', format=json)).split(" ")[3])
            wait_counter=1

            #Truncated Backoff
            #Issue is that with multiple threads calling bulk_import the write queue gets filled up and starts dropping 
            #the request, by implementing a throttle with an truncated backoff we ensure that the 
            # likelyhood of the write queue maxing out is reduced.

            #TODO dynamically identify max number of threads for throttling, currently set thread count to 25
            while bulk_status > 25:
                wait_time = 10 * wait_counter
                logging.warn("bulk thread pool high(%s), throttling for %s seconds" % (bulk_status, wait_time))
                time.sleep(wait_time)

                if wait_counter == 4:
                    wait_counter = 1
                else:
                    wait_counter += 1

                bulk_status = int((es.cat.thread_pool(thread_pool_patterns='write', format=json)).split(" ")[3])

            logging.info('Bulk indexing')
            #call parallel_bluk API to index all documents captured in actions
            deque(helpers.parallel_bulk(es, actions, chunk_size=1000, thread_count=1, request_timeout=60), maxlen=0)
            #logging.info("indexing complete...")
            index = False
        except Exception as e:
            #Setup structure/capture errors received from elasticsearch 
            error_doc = {}
            error_status_ary = []
            error_doc = e.args
            error_type = type(e)
            try:
                #list our all errors received from elasticsearch
                for i in error_doc:
                    if isinstance(i, list):
                        for j in i:
                            if j['index']['status'] not in error_status_ary:
                                error_status_ary.append(j['index']['status'])

                for i in error_status_ary:
                        logging.error("Failed to index - Status: %s - %s" % (i, type(e)))
            except:
                #unable to identify errors
                logging.error("Failed to index, unknown error)
"

**Comment by portante** [comment]
Implemented with #7.
